import { anios, unidadCompra } from 'mockup'

export const OCForm = {
	fieldsById: {
		nombreOC: {
			name: 'nombreOC',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 8,
		},
		despachoObservacion: {
			name: 'despachoObservacion',
			label: 'Observación de despacho',
			required: false,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Ingresar observaciones o indicaciones para el despacho',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		plazoPago: {
			name: 'plazoPago',
			label: 'Plazo de pago',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			placeholder: 'Ingresar observaciones o indicaciones para el pago',
			value: '1',
			items: [
				{ id: '1', label: '45 días contra la recepción de la factura' },
				{
					id: '2',
					label:
						'45 días contra la recepción de la factura (para institución de salud)',
				},
				{ id: '3', label: 'Mayor a 30 días' },
			],
			rule: { type: 'null' },
		},
		pagoJustificacion: {
			name: 'pagoJustificacion',
			label:
				'Ha seleccionado plazo de entrega mayor a 30 días, debe ingresar una justificación',
			required: true,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Motivo de pago mayor a 30 días...',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		nombreContactoCompra: {
			name: 'nombreContactoCompra',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		apellidoContactoCompra: {
			name: 'apellidoContactoCompra',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		telefonoContactoCompra: {
			name: 'telefonoContactoCompra',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			mode: 'phone',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		emailContactoCompra: {
			name: 'emailContactoCompra',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 3,
		},
		nombreContactoPago: {
			name: 'nombreContactoPago',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		apellidoContactoPago: {
			name: 'apellidoContactoPago',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		telefonoContactoPago: {
			name: 'telefonoContactoPago',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			mode: 'phone',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		emailContactoPago: {
			name: 'emailContactoPago',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 3,
		},
		indicacionesFactura: {
			name: 'indicacionesFactura',
			label: 'indicaciones',
			required: false,
			isValid: true,
			status: 'default',
			type: 'text',

			value: '',
			rule: { type: 'range', min: 5, max: 50 },
			md: 6,
			rows: 1,
		},
		emailEnvioFactura: {
			name: 'emailEnvioFactura',
			label: 'Email',
			required: false,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 3,
		},
		asociarPlanCompra: {
			name: 'asociarPlanCompra',
			label: '¿Desea asociar al Plan de compras?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: null,
			items: [
				{
					id: '1',
					label: 'Sí',
				},
				{ id: '2', label: 'No, esta compra está fuera del Plan de compras' },
			],
			rule: { type: 'null' },
		},
		documentosAdjuntar: {
			name: 'documentosAdjuntar',
			label: '¿Qué documentos desea adjuntar?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: null,
			items: [
				{
					id: '1',
					label: 'Resolución o decreto',
				},
				{ id: '2', label: 'Otro documento anexo' },
			],
			rule: { type: 'null' },
		},
		autoriza: {
			name: 'autoriza',
			label: '¿Quién autoriza esta Orden de Compra?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: null,
			items: [
				{
					id: '1',
					label: 'Yo autorizo esta Orden de Compra',
				},
				{ id: '2', label: 'Otros autorizadores lo harán' },
			],
			rule: { type: 'null' },
		},
	},
}

export const itemsAsociadosfiltersFieldsById = {
	anios: {
		name: 'anios',
		label: 'Año del proyecto',
		required: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: anios,
		md: 6,
	},
	unidad_compra: {
		name: 'unidad_compra',
		label: 'Unidad de compra',
		required: true,
		disabled: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: unidadCompra,
		md: 6,
	},
}

export const autorizadoresfiltersFieldsById = {
	unidad_compra: {
		name: 'unidad_compra',
		label: 'Unidad de compra',
		required: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: [],
		md: 6,
	},
	anios: {
		name: 'anios',
		label: 'Año del proyecto',
		required: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: anios,
		md: 6,
	},
}
