import { anios, unidadCompra } from 'mockup'

export const OCForm = {
	fieldsById: {
		nombreOC: {
			name: 'nombreOC',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 8,
		},
		despacho_observacion: {
			name: 'despacho_observacion',
			label: 'Observación de despacho',
			required: false,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Ingresar observaciones o indicaciones para el despacho',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		plazo_pago: {
			name: 'plazo_pago',
			label: 'Plazo de pago',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			placeholder: 'Ingresar observaciones o indicaciones para el pago',
			value: '1',
			items: [
				{ id: '1', label: '45 días contra la recepción de la factura' },
				{
					id: '2',
					label:
						'45 días contra la recepción de la factura (para institución de salud)',
				},
				{ id: '3', label: 'Mayor a 30 días' },
			],
			rule: { type: 'null' },
		},
		pago_observacion: {
			name: 'pago_observacion',
			label: 'Observación de pago',
			required: true,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Ingresar observaciones o indicaciones para el despacho',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		pago_justificacion: {
			name: 'pago_justificacion',
			label:
				'Ha seleccionado plazo de entrega mayor a 30 días, debe ingresar una justificación',
			required: true,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Motivo de pago mayor a 30 días...',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		nombre_contacto_compra: {
			name: 'nombre_contacto_compra',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		apellido_contacto_compra: {
			name: 'apellido_contacto_compra',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		telefono_contacto_compra: {
			name: 'telefono_contacto_compra',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		email_contacto_compra: {
			name: 'email_contacto_compra',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 3,
		},
		nombre_contacto_pago: {
			name: 'nombre_contacto_pago',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		apellido_contacto_pago: {
			name: 'apellido_contacto_pago',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		telefono_contacto_pago: {
			name: 'telefono_contacto_pago',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 3,
		},
		email_contacto_pago: {
			name: 'email_contacto_pago',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 3,
		},
		email_envio_factura: {
			name: 'email_envio_factura',
			label: 'Email',
			required: false,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 6,
		},
		asociar_plan_compra: {
			name: 'asociar_plan_compra',
			label: '¿Desea asociar al Plan de compras?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: '2',
			items: [
				{
					id: '1',
					label: 'Sí',
				},
				{ id: '2', label: 'No, esta compra está fuera del Plan de compras' },
			],
			rule: { type: 'null' },
		},
		documentos_adjuntar: {
			name: 'documentos_adjuntar',
			label: '¿Qué documentos desea adjuntar?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: '1',
			items: [
				{
					id: '1',
					label: 'Resolución o decreto',
				},
				{ id: '2', label: 'Otro documento anexo' },
			],
			rule: { type: 'null' },
		},
		autoriza: {
			name: 'autoriza',
			label: '¿Quién autoriza esta Orden de Compra?',
			required: true,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: '2',
			items: [
				{
					id: '1',
					label: 'Yo autorizo esta Orden de Compra',
				},
				{ id: '2', label: 'Otros autorizadores lo harán' },
			],
			rule: { type: 'null' },
		},
	},
}

export const itemsAsociadosfiltersFieldsById = {
	anios: {
		name: 'anios',
		label: 'Año del proyecto',
		required: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: anios,
		md: 6,
	},
	unidad_compra: {
		name: 'unidad_compra',
		label: 'Unidad de compra',
		required: true,
		disabled: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: unidadCompra,
		md: 6,
	},
}

export const autorizadoresfiltersFieldsById = {
	unidad_compra: {
		name: 'unidad_compra',
		label: 'Unidad de compra',
		required: true,
		isValid: true,
		status: 'default',
		type: 'select',
		value: -1,
		rule: { type: 'select' },
		items: unidadCompra,
		md: 6,
	},
}
