export const OCForm = {
	fieldsById: {
		despacho_observacion: {
			name: 'despacho_observacion',
			label: 'Observación de despacho',
			required: false,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Ingresar observaciones o indicaciones para el despacho',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		plazo_pago: {
			name: 'plazo_pago',
			label: 'Plazo de pago',
			required: false,
			isValid: true,
			status: 'default',
			type: 'radio',
			placeholder: 'Ingresar observaciones o indicaciones para el pago',
			value: '1',
			items: [
				{
					id: '1',
					label: '30 días contra la recepción conforme de la factura',
				},
				{ id: '2', label: 'Mayor a 30 días' },
			],
			rule: { type: 'null' },
		},
		pago_observacion: {
			name: 'pago_observacion',
			label: 'Observación de pago',
			required: false,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Ingresar observaciones o indicaciones para el despacho',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		pago_justificacion: {
			name: 'pago_justificacion',
			label:
				'Ha seleccionado plazo de entrega mayor a 30 días, debe ingresar una justificación',
			required: false,
			isValid: true,
			status: 'default',
			type: 'textarea',
			placeholder: 'Motivo de pago mayor a 30 días...',
			value: '',
			rule: { type: 'range', min: 5, max: 50 },
		},
		nombre_contacto_compra: {
			name: 'nombre_contacto_compra',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		apellido_contacto_compra: {
			name: 'apellido_contacto_compra',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		telefono_contacto_compra: {
			name: 'telefono_contacto_compra',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		email_contacto_compra: {
			name: 'email_contacto_compra',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 6,
		},
		nombre_contacto_pago: {
			name: 'nombre_contacto_pago',
			label: 'Nombre',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		apellido_contacto_pago: {
			name: 'apellido_contacto_pago',
			label: 'Apellido',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		telefono_contacto_pago: {
			name: 'telefono_contacto_pago',
			label: 'Teléfono',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'range', min: 1, max: 50 },
			md: 6,
		},
		email_contacto_pago: {
			name: 'email_contacto_pago',
			label: 'Email',
			required: true,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 6,
		},
		email_envio_factura: {
			name: 'email_envio_factura',
			label: 'Email',
			required: false,
			isValid: true,
			status: 'default',
			type: 'text',
			value: '',
			rule: { type: 'email' },
			md: 6,
		},
		asociar_plan_compra: {
			name: 'asociar_plan_compra',
			label: '¿Desea asociar al Plan de compras?',
			required: false,
			isValid: true,
			status: 'default',
			type: 'radio',
			value: '2',
			items: [
				{
					id: '1',
					label: 'Sí',
				},
				{ id: '2', label: 'No, esta compra está fuera del Plan de compras' },
			],
			rule: { type: 'null' },
		},
	},
}
